### ISSUE TITLE
Accept input from stdin

### ISSUE THREAD

**Issue by HarrisonMc555** [Lateralus138/onlyone#1]
I was going to use this tool, but it doesn't appear to accept input from stdin. Which makes it unusable for me since I prefer to pipe things into other commands without saving them in temporary files. If you add this feature maybe I'll try it! The tool looks nice for your use case, though :smiley:

**Comment by Lateralus138** [comment]
Yeah I originally wrote this really quick just for myself (as I do most things) and Rust is one of my newer languages so I wasn't real focused on it at the time, just wanted to see what I could do with it ( I just use this to automate removal of duplicate lines in .bash_history, I know, there's other ways), but I do have stdin planned; *eventually*.

I export to a backup just in case so I had no need for a pipe at the time.

I'm more of a hobbyist now and have several projects going in C++ and so it may be a while, sorry. And to be honest I'll probably be re-writing this in C++ as I am far more familiar with the language than Rust (like by 20+ years) and to be honest I have just been playing around with Rust. I like it, but I'm not pro at it.

This is on the todo list though.

Appreciate the feedback. I'll keep this open as a reminder.

**Comment by Lateralus138** [comment]
I spent some time today building a framework for a ***C++*** version of this so it's ready to  build after I release a couple more programs. It prepends `stdin` lines to the vector line queue and skips case sensitive duplicates. Thinking about throwing a case insensitive switch in there.

Current progress:
![Screenshot from 2021-06-23 13-50-16](https://user-images.githubusercontent.com/21045862/123152237-fee37800-d429-11eb-9296-000e9b1ba0e5.png)

Current Help Screen:
![Screenshot from 2021-06-23 18-05-40](https://user-images.githubusercontent.com/21045862/123179241-98248580-d44e-11eb-82d9-cdef01fe7521.png)

**Comment by Lateralus138** [comment]
This project is now fairly redundant, though I'll leave it up, but I'm finished with the official 2nd version **OnlyOne V2**. 

Since I do not plan to add this feature for the Rust version I'm going to close this issue.

Thank you for inspiring me to move this up on my todo list.

If you are still interested you can find it here:
[OnlyOneV2@GitHub](https://github.com/Lateralus138/onlyonev2)

**Comment by Lateralus138** [comment]
This project is now fairly redundant, though I'll leave it up, but I'm finished with the official 2nd version **OnlyOne V2**. 

Since I do not plan to add this feature for the Rust version I'm going to close this issue.

Thank you for inspiring me to move this up on my todo list.

If you are still interested you can find it here:
[OnlyOneV2@GitHub](https://github.com/Lateralus138/onlyonev2)
